### PR TITLE
fix(useHandleForm): Removed console log

### LINKED ISSUE #43: Clean up console.error when running tests
When running tests, the following is printed in the terminal. If this is what the end user gets when an error occurs with `useHandleForm` we should clean that up. @heythisispaul 
```
PASS __tests__/hooks/useHandleForm.js
  ● Console

    console.error src/hooks/useHandleForm.js:30
      Error: error time
          at C:\Users\james\Documents\coding\hooks-arsenal\__tests__\hooks\useHandleForm.js:69:52
          at finalReturnValue (C:\Users\james\Documents\coding\hooks-arsenal\node_modules\jest-mock\build\index.js:480:41)
          at C:\Users\james\Documents\coding\hooks-arsenal\node_modules\jest-mock\build\index.js:489:13
          at submitFunction (C:\Users\james\Documents\coding\hooks-arsenal\node_modules\jest-mock\build\index.js:182:19)
          at handleSubmit$ (C:\Users\james\Documents\coding\hooks-arsenal\src\hooks\useHandleForm.js:24:28)
          at tryCatch (C:\Users\james\Documents\coding\hooks-arsenal\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:45:40)  
          at Generator.invoke [as _invoke] (C:\Users\james\Documents\coding\hooks-arsenal\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:271:22)
          at Generator.prototype.(anonymous function) [as next] (C:\Users\james\Documents\coding\hooks-arsenal\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:97:21)
          at tryCatch (C:\Users\james\Documents\coding\hooks-arsenal\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:45:40)  
          at invoke (C:\Users\james\Documents\coding\hooks-arsenal\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:135:20)   
          at C:\Users\james\Documents\coding\hooks-arsenal\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:170:11
          at new Promise (<anonymous>)
          at callInvokeWithMethodAndArg (C:\Users\james\Documents\coding\hooks-arsenal\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:169:16)
          at AsyncIterator.enqueue (C:\Users\james\Documents\coding\hooks-arsenal\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:192:13)
          at AsyncIterator.prototype.(anonymous function) [as next] (C:\Users\james\Documents\coding\hooks-arsenal\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:97:21)
          at Object.<anonymous>.exports.async (C:\Users\james\Documents\coding\hooks-arsenal\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:216:14)
          at Object.handleSubmit (C:\Users\james\Documents\coding\hooks-arsenal\src\hooks\useHandleForm.js:18:24)
          at C:\Users\james\Documents\coding\hooks-arsenal\__tests__\hooks\useHandleForm.js:76:22
          at batchedUpdates (C:\Users\james\Documents\coding\hooks-arsenal\node_modules\react-test-renderer\cjs\react-test-renderer.development.js:14454:12)
          at act (C:\Users\james\Documents\coding\hooks-arsenal\node_modules\react-test-renderer\cjs\react-test-renderer.development.js:17271:14)    
          at _callee3$ (C:\Users\james\Documents\coding\hooks-arsenal\__tests__\hooks\useHandleForm.js:75:5)
          at tryCatch (C:\Users\james\Documents\coding\hooks-arsenal\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:45:40)  
          at Generator.invoke [as _invoke] (C:\Users\james\Documents\coding\hooks-arsenal\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:271:22)
          at Generator.prototype.(anonymous function) [as next] (C:\Users\james\Documents\coding\hooks-arsenal\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:97:21)
          at tryCatch (C:\Users\james\Documents\coding\hooks-arsenal\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:45:40)  
          at invoke (C:\Users\james\Documents\coding\hooks-arsenal\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:135:20)   
          at C:\Users\james\Documents\coding\hooks-arsenal\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:170:11
          at new Promise (<anonymous>)
          at callInvokeWithMethodAndArg (C:\Users\james\Documents\coding\hooks-arsenal\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:169:16)
          at AsyncIterator.enqueue (C:\Users\james\Documents\coding\hooks-arsenal\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:192:13)
          at AsyncIterator.prototype.(anonymous function) [as next] (C:\Users\james\Documents\coding\hooks-arsenal\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:97:21)
          at Object.<anonymous>.exports.async (C:\Users\james\Documents\coding\hooks-arsenal\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:216:14)
          at Object._callee3 (C:\Users\james\Documents\coding\hooks-arsenal\__tests__\hooks\useHandleForm.js:67:43)
          at Object.asyncJestTest (C:\Users\james\Documents\coding\hooks-arsenal\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:102:37)     
          at resolve (C:\Users\james\Documents\coding\hooks-arsenal\node_modules\jest-jasmine2\build\queueRunner.js:43:12)
          at new Promise (<anonymous>)
          at mapper (C:\Users\james\Documents\coding\hooks-arsenal\node_modules\jest-jasmine2\build\queueRunner.js:26:19)
          at promise.then (C:\Users\james\Documents\coding\hooks-arsenal\node_modules\jest-jasmine2\build\queueRunner.js:73:41)```

### PR DESCRIPTION
**Pull request by heythisispaul**
# Remove console log on error in UseHandleForm

## Description

Removes `console.error` when catching an error in `useHandleForm` and makes the error object the value of `submitResult` (in the event of an error). This means it's still exposed to the component it's called in so the developer can do what they want with it, but they're not forced to log anything by using this hook. This means no log is emitted by this hook in its usage or in the tests.

Fixes #43

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested

See attached:
testresults

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by heythisispaul** [comment]
Do you think it's having the MFA on my github account that was preventing the forked branches from being able to be checked?

**Comment by JamesSingleton** [comment]
I don't think it was, or it shouldn't of been. Also, should we error if there is but maybe use something other than console.error?

**Comment by heythisispaul** [comment]
Sure, what else were you thinking? We could warn or simply log.

We could still remove that big red block by wrapping `console` in a `jest.spyOn` and mocking the implementation for that test that throws the error.

**Comment by JamesSingleton** [comment]
Could we use something like https://www.npmjs.com/package/invariant possibly?

**Comment by JamesSingleton** [comment]
Also, I missed this on the initial PR, but your test file is missing `.spec`. Do you mind adding that as well?

**Comment by JamesSingleton** [comment]
@heythisispaul any update on this PR?

**Comment by heythisispaul** [comment]
@JamesSingleton sorry I fell off the wagon there for a bit. 

I definitely think it needs to error. That way the `experiencedError` state is updated, so that the user knows to handle that result. I'm okay with using invariant, if we do I think we should make that the standard across all hooks. What do you think?

**Comment by JamesSingleton** [comment]
@heythisispaul

I agree let's make it standard.

**Comment by JamesSingleton** [comment]
Actually... The more I think about this, I am not sure if invariant is the way to go here. Thoughts?

**Pull request merged**
